### ISSUE TITLE
Data base script does not work for a windows 32bit system

### ISSUE THREAD

**Issue by eantigha** [chai-lmis/N-LMIS#4]

**Comment by hemantyusata** [comment]
Sourabh had resolved this issue, when emma bring this issue in our notice. And we created separate scripts for 32bit and 64bit systems.
So, this issue was resolved at that time already.

**Comment by almightyphoenix** [comment]
This issue had resolved at the time when emma bring this in our notice. We have created separate scripts for 32bit and 64bit systems.
So, this issue is resolved and done!
